export const ADD_ATHLETE_TO_WATCH = 'ADD_ATHLETE_TO_WATCH';
export const REMOVE_ATHLETE_FROM_WATCH = 'REMOVE_ATHLETE_FROM_WATCH';
export const REMOVE_ALL_ATHLETES_FROM_WATCH = 'REMOVE_ALL_ATHLETES_FROM_WATCH';
export const NEW_ATHLETE_INPUT_FIRST = 'NEW_ATHLETE_INPUT_FIRST';
export const NEW_ATHLETE_INPUT_LAST = 'NEW_ATHLETE_INPUT_LAST';
export const CREATE_ATHLETE = 'CREATE_ATHLETE';
export const CREATE_ATHLETE_ERROR = 'CREATE_ATHLETE_ERROR';
export const RESET_ATHLETE_LIST = 'RESET_ATHLETE_LIST';
