"use strict";

export const START_WATCH = "START_WATCH";
export const STOP_WATCH = "STOP_WATCH";
export const TICK = "TICK";
export const RESET_ALL = "RESET_ALL";
export const RESET_TIME = "RESET_TIME";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const NEW_ATHLETE_INPUT = "NEW_ATHLETE_INPUT";
export const ADD_ATHLETE = "ADD_ATHLETE";
export const ADD_ATHLETE_ERROR = "ADD_ATHLETE_ERROR";
export const ADD_SPLIT = "ADD_SPLIT";
export const MODE_CHANGE = "MODE_CHANGE";
export const RESET_ATHLETE_LIST = "RESET_ATHLETE_LIST";
export const ADD_HISTORY = "ADD_HISTORY";
export const REMOVE_ATHLETE_FROM_WATCH = "REMOVE_ATHLETE_FROM_WATCH";
export const ADD_ATHLETE_TO_WATCH = "ADD_ATHLETE_TO_WATCH";
export const DELETE_ATHLETE = "DELETE_ATHLETE";
export const DELETE_HISTORY = "DELETE_HISTORY";
