# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'TeamWatch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeamWatch

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Auth'
pod 'Firebase/Database'
  

  target 'TeamWatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TeamWatch-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeamWatch-tvOS

  target 'TeamWatch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
